### ISSUE TITLE
Installer: "Failed to get fw version" if 0syscall6 plugin was enabled

### ISSUE THREAD

**Issue by dogtopus** [SKGleba/enso_ex#22]

**Comment by SKGleba** [comment]
I am aware of the issue - secure_kernel.enp is modified in memory by 0syscall6. Enso uses its version to detect the current true fw version. I have mentioned in the readme that booting while holding LT will fix that (0syscall6 is skipped).
This issue should not be present on HFW since it uses a different 0syscall6.
