### ISSUE TITLE
Softbricked My PSVita

### ISSUE THREAD

**Issue by MrTech999** [SKGleba/enso_ex#4]
Accidentaly turned on the sd2vita drivers. No problem I thought till i reboot and find it disables the memory card. Can I have any way to fix this?!

**Comment by BombBloke** [comment]
Your options are to either get an SD2Vita, or to re-install a clean copy of your firmware through safe mode.

If you also turned on the update blocker then it'll furthermore block you from re-installing your firmware. You can work around this by plugging into a charger once the PUP file has copied over, however.

**Comment by MrTech999** [comment]
Turns out that update blocker is on and I cant even reinstall h-encore with out a memory card.But the usb port is broke and I can only charge from it and not do any file transfers from usb only by FTP, so I am bascially screwed. Going to have to buy a sd2vita now

**Comment by leilancet** [comment]
> Your options are to either get an SD2Vita, or to re-install a clean copy of your firmware through safe mode.
> 
> If you also turned on the update blocker then it'll furthermore block you from re-installing your firmware. You can work around this by plugging into a charger once the PUP file has copied over, however.
I HAVE THE same problem..I turn on the update blocker and the sd2vita driver, and bricked!!!!! psvita can"t read the memory card. and I got an SD2VITA, formated then it cannot be read either. when SD2Vita is inserted the PSvita takes forever to boot. When i get it out, it continues to boot. When i try to shut it down it won’t till i eject the card. what can i do..

**Comment by leilancet** [comment]
how to re-install a clean copy of your firmware through safe mode?

**Comment by humbird0** [comment]
I was able to get Enso EX to work, but not without some issues at first.

Like most people, when I ran Enso EX I chose to enable SD2vita, then after rebooting it wasn't reading either the SD card nor the SONY memory card.
Then I tried removing my SONY memory card from the bottom. After rebooting it read the SD2Vita card just fine.
Re-inserting the SONY card caused a reboot and it went back to not reading either of them.
So I took out the SONY card, booted with the sd2vita card, ran Enso EX again, and chose NOT to use the sd2vita option. This fixed the problem. After rebooting, it was reading the SD card, and if I rebooted without the sd2vita it read the SONY card just like before.
So the issue seems to be Enso EX's sd2vita driver having messed up priorities. Just skip using it, and use something else to mount the sd2vita. I myself have been using the "switch_sd2vita" homebrew.

This might not work for everyone. I'm using a gen1 vita with no internal storage, so I was able to remove the SONY memory card. My exact setup was this:
Gen1 Vita.
Firmware 3.65
Hacked with FinalHE version 1.5
Originally used Enso version 1.1
Used SwitchSD2Vita homebrew to auto-mount the sd2vita cartridge adapter
... THEN I attempted to use Enso EX, and went through the steps above.

**Comment by Plausible0Bug** [comment]
My PSV 2000 is brick by SD2VITA driver as well today, to make things worse this modifications somehow survived an update from 3.60 to 3.65 and rendered internal 1GB storage unusable.

Would urge you to disable this dangerous feature immediately.

If you have any advice to me personally, I would appreciate it.

**Comment by Plausible0Bug** [comment]
I'm currently out of ideas, as I also blocked upgrade at the meantime I cannot reinstall clean firmware.

**Comment by Plausible0Bug** [comment]
Should there be a way to disable all modifications upon boot?

Now my PSV can't even detect external Sony Memory Card.

**Comment by Plausible0Bug** [comment]
I'm able to recover by using safe mode and feeding a firmware which is the same version I already have via qcma.

After which I can see my internal 1GB storage come back and continue by installing h-encore.


Leave a comment below if you need assistance.

**Comment by montero3006** [comment]
Hello, i have exactly the same problem, a PSVITA2000 that not read SD2VITA or internal memory or memory cards. Not read anything and can´t update , FW is 3.60 and recovery mode says is up to date. Any suggestion? Thanks!

**Comment by Plausible0Bug** [comment]
@montero3006 how are you feeding the firmware to your PSV ?

Do you have QCMA and QCMA USB driver properly installed?

**Comment by Plausible0Bug** [comment]
Here is a detailed tutorial, try following it:

https://www.reddit.com/r/vitahacks/comments/b4z3ez/faq_enso_ex_v30/

**Comment by leilancet** [comment]
I think you only have to find a usable SD2VITA adapter (you can buy more SD2VITA cards at a time, make sure at least one is working properly). Follow the SD2Vita Tutorial Instructions by google, Prepare your microSD card.

Download  Win32 Disk Imager

Open Win32 Disk Imager and select zzBlank.img that you downloaded earlier

Select your microSD and click Write

Take your microSD card out of your computer and put it back in

Windows will prompt you to format your card. Use these settings.
File System: exFat

Allocation Unit Size: Default Allocation Size

Do not put a volume label. Leave blank.

Enable Quick Format if you wish.

6. Copy the SD2Vita driver file (gamesd.skprx) to microSD, in tai/gamesd.skprx. you need to create a folder named tai
7.Put the SD Card into the SD2Vita adapter and reboot your Vita
8.Hold down the R, PS, and power buttons to enter vita safe mode.
9.Rebuild the database to repair
 




------------------ 原始邮件 ------------------
发件人: "montero3006"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 凌晨3:31
收件人: "SKGleba/enso_ex"<enso_ex@noreply.github.com>;
抄送: "星星之火"<314189929@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [SKGleba/enso_ex] Softbricked My PSVita (#4)




Hello, i have exactly the same problem, a PSVITA2000 that not read SD2VITA or internal memory or memory cards. Not read anything and can´t update , FW is 3.60 and recovery mode says is up to date. Any suggestion? Thanks!

**Comment by SKGleba** [comment]
Everything will be skippable and checked in v4, thanks for your feedback, and sorry for all the troubles.
